services:
  watered:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Production server configuration
      PORT: "8080"
      ENVIRONMENT: "production"
      
      # Security settings
      SECURE_COOKIES: "true"
      HTTPS_ONLY: "true"
      
      # Database configuration
      DATABASE_PATH: "/home/watered/data/watered.db"
      
      # These should be provided via .env file or environment
      # Do not set sensitive values directly in this file
      # GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      # GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # SESSION_SECRET: ${SESSION_SECRET}
      # ALLOWED_EMAILS: ${ALLOWED_EMAILS}
      # ADMIN_EMAILS: ${ADMIN_EMAILS}
    volumes:
      # Persistent data volume for application state
      - watered_data:/home/watered/data
      # Optional: mount custom web assets (if customizing)
      # - ./web:/home/watered/web:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Don't expose port directly in production - use nginx
    expose:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment for SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      watered:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Define named volumes
volumes:
  watered_data:
    driver: local
    # Uncomment for external volume (e.g., mounted disk)
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /opt/watered/data

# Optional: Define networks for better isolation
networks:
  default:
    name: watered_network